### ISSUE TITLE
Fundo infinito perde o posicionamento após a morte

### ISSUE THREAD

**Issue by loloop** [dedig/dedig-game-jam-1#8]
@lucasvinbr favor postar imagem

**Comment by lucasvinbr** [comment]
![screenshot_2015-04-28-19-30-39](https://cloud.githubusercontent.com/assets/6752938/7413479/a7f3d096-ef22-11e4-8346-5e1177fc2da9.png)

**Comment by lucasvinbr** [comment]
Arrumado no commit 8f0f91df8abc828e3a10de056cc697100c055346
